### ISSUE TITLE
抓取的图片变花

### ISSUE THREAD

**Issue by usernamefucku** [kfstorm/BingWallpaper#5]
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/112452099/187332605-c05944cd-6303-4c83-9dd4-184a8c677570.png">
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/112452099/187332651-f3f7262f-111e-43d1-b7d8-ec938cc7c0fb.png">
如上图所示，不是每天都这样，偶尔的时候会出现这种问题。软件用了好多年了，从win7用到win11，非常好用，希望能解决问题

**Comment by kfstorm** [comment]
先打开`%APPDATA%\K.F.Storm\BingWallpaper`这个目录。

1. 检查一下该目录下的图片文件是否有问题。
2. 看一下log.log这个日志文件里有没有什么报错。
3. 看一下state.xml里记录的`PictureUrl`，用浏览器打开看看图片是否有问题。

**Comment by usernamefucku** [comment]
1、检查目录发现图片文件有问题，如下图，这是20220901抓取的图片
![image](https://user-images.githubusercontent.com/112452099/187825815-dce1d87c-0e6d-4488-a74e-bc245491715b.jpg)
2、貌似有一些报错，但是看不太明白，不知是否和这个问题有关联
[log.log](https://github.com/kfstorm/BingWallpaper/files/9466640/log.log)
3、state.xml里记录的PictureUrl，用浏览器打开图片没问题，图片如下
![image](https://user-images.githubusercontent.com/112452099/187826349-59f106f1-18da-4268-a8c6-b16940da02df.png)

**Comment by usernamefucku** [comment]
1、检查目录发现图片文件为花图，这是20220901抓取的图片
<img width="804" alt="微信截图_20220901114044" src="https://user-images.githubusercontent.com/112452099/187826911-74151b7c-e3b2-473d-9595-8dda258d79e1.png">

2、貌似有一些报错，但是看不太明白，不知是否和这个问题有关联
[log.log](https://github.com/kfstorm/BingWallpaper/files/9466672/log.log)


3、state.xml里记录的PictureUrl，用浏览器打开图片没问题，图片如下
<img width="566" alt="微信截图_20220901114259" src="https://user-images.githubusercontent.com/112452099/187827079-2d5a9cdd-3589-4600-8e9f-d188254baf45.png">

**Comment by kfstorm** [comment]
能否将有问题的图片和没有问题的图片一起打个zip包上传到这里？我对比一下文件内容。我现在看到的图片都是png格式的，但是我记得bing提供的应该是jpg的图片，可能github自动做了转换。

**Comment by kfstorm** [comment]
对了，麻烦说一下系统环境和.NET版本。

**Comment by usernamefucku** [comment]
抱歉，我没说清楚，png格式是因我在github上传时采用了截图上传方式，原图格式都是jpg的。
附件：
[K.F.Storm.zip](https://github.com/kfstorm/BingWallpaper/files/9469372/K.F.Storm.zip)
操作系统：Windows 11 专业版 (64 位) 21H2 (10.0.22000)
.NET 3.5和 .NET 4.8均已启用
![image](https://user-images.githubusercontent.com/112452099/187902530-bfbf63fe-a3fc-409a-81f4-3812f7532613.png)

**Comment by usernamefucku** [comment]
![image](https://user-images.githubusercontent.com/112452099/188527409-48b8a92e-015f-4428-8f50-33a37669234d.png)
补充.net详细版本

**Comment by kfstorm** [comment]
不是很清楚原因，看起来下载下来的文件有很多处地方都和源文件不一致。会不会是你使用了代理软件之类的，代理软件有问题？

![image](https://user-images.githubusercontent.com/3626358/188546301-cd645501-0759-4c2d-b592-66b907ed6b08.png)

**Comment by kfstorm** [comment]
你可以试一下这个版本，我把HTTP链接换成了HTTPS链接，这样应该就不会发生内容被篡改的情况了。
[bin.zip](https://github.com/kfstorm/BingWallpaper/files/9493291/bin.zip)

如果用了一段时间没有问题，麻烦反馈一下。

**Comment by usernamefucku** [comment]
我并没有使用过代理类的软件，这个问题上周比较频繁的出现，这周还好。我试用一到两周，后续使用情况再来反馈，谢谢！

**Comment by usernamefucku** [comment]
用了半个月了，目前没有再出现变花现象，感谢作者
